apiVersion: v1
kind: Service
metadata:
  name: spark-history-service
  namespace: spark
spec:
  type: LoadBalancer
  ports:
  - port: 18080
    targetPort: 18080
  selector:
    app: spark-history
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-deployment
  namespace: spark
spec:
  selector:
    matchLabels:
      app: spark-history
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-history
    spec:
      serviceAccountName: spark-sa
      containers:
      - name: spark-history
        image: anildwacontainerregistry.azurecr.io/spark-history:3.0.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
        command:
            -  /usr/bin/tini
            - -s
            - --
            - /opt/spark/bin/spark-class
            - -Dspark.hadoop.fs.azure.account.key.anildwastoragewestus2.dfs.core.windows.net=VtabaLSS+KyPsJQBElXGV+4wD5tMOeL8glotVXCNwqptiRgD/QjZ1ntEyWEekl6VGnGFt4n7e8TBk0/4uI2k7g==
            - -Dspark.history.fs.logDirectory=abfss://spark-event-logs@anildwastoragewestus2.dfs.core.windows.net/logs
            - org.apache.spark.deploy.history.HistoryServer
        ports:
          - name: http
            protocol: TCP
            containerPort: 18080
